version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: coaching_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: coaching_management
    networks:
      - coaching_management

networks:
  coaching_management:
